@@include('libs/gsap.min.js', {})
@@include('libs/SplitText.min.js', {})
@@include('libs/ScrollTrigger.min.js', {})
@@include('libs/ScrollToPlugin.min.js', {})
@@include('libs/swiper-bundle.min.js', {})